name: CI
on: [pull_request, workflow_dispatch, push]

jobs:
  build_windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v1

      - name: Set up Cygwin
        uses: egor-tensin/setup-cygwin@v4

      - name: Download Submodules
        run: git submodule update --init --recursive

      - name: Build TB
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat
          make package -j
        timeout-minutes: 10

      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: tb-windows
          path: tb.tar.gz
  build_mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1

      - name: Download LLVM and Make
        run: |
          brew update
          brew install llvm@14 make

      - name: Download Submodules
        run: git submodule update --init --recursive

      - name: Build TB
        run: make package -j
        timeout-minutes: 10

      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: tb-macos
          path: tb.tar.gz
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Download LLVM
        run: sudo apt-get install llvm-11 clang-11

      - name: Download Submodules
        run: git submodule update --init --recursive

      - name: Build TB
        run: make package -j
        timeout-minutes: 10

      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: tb-linux
          path: tb.tar.gz
