name: CI
on: [pull_request, workflow_dispatch, push]

jobs:
  build_windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v1
      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: Download Submodules
        run: git submodule update --init --recursive

      - name: Build TB
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat
          py build.py x64 aarch64 wasm
        timeout-minutes: 10
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: seanmiddleditch/gha-setup-ninja@master
      - name: Download LLVM
        run: sudo apt-get install llvm-11 clang-11

      - name: Download Submodules
        run: git submodule update --init --recursive

      - name: Build TB
        run: python3 build.py x64 aarch64 wasm
        timeout-minutes: 10
